LOCAL_PATH := $(call my-dir)

# MiXplorer
include $(CLEAR_VARS)
LOCAL_MODULE := MiXplorer
LOCAL_OVERRIDES_PACKAGES :=  Jelly Browser Browser2 GalleryGoPrebuilt
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := MiXplorer.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_PRODUCT_MODULE := true
include $(BUILD_PREBUILT)

# GCamGOPrebuilt
include $(CLEAR_VARS)
LOCAL_MODULE := GCamGOPrebuilt
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := priv-app/GCamGOPrebuilt/GCamGOPrebuilt.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_OVERRIDES_PACKAGES := Snap Camera Camera2 SnapdragonCamera
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)

# SimpleGallery
include $(CLEAR_VARS)
LOCAL_MODULE := SimpleGallery
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := priv-app/SimpleGallery/SimpleGallery.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_OVERRIDES_PACKAGES := Gallery2 Gallery3d Gallery GalleryGo SnapdragonGallery
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)
